- system/login/login.php
> update login form

- header.php
- index.php
- system/js/script.js
- system/js/struc.txt
- system/login/register.php
Javascript und PHP Grundlage für das Loginsystem erstellt.
> Login, Register und Session

- index.php
- system/functions.php
- system/login/activation.php
- system/login/login.php
Aktivierung funktioniert nun. Einige Provisorien sind noch vorhanden, außerdem müssen wir schauen wie wir das Problem mit der dbpre Variable in prepared Statements lösen.
> Prototyp Aktivierung fertiggestellt

- sidebar.php
- styles/style.css
Sollte noch anders gelöst werden (zB. ein- und ausklappen der sidebar über js, automatisches einklappen bei kleinen bildschirmen?)
> Sidebar-Problem mit kleinen Bildschirmen vorläufig gelöst

- system/functions.php
- system/login/login.php
> Login Prototyp fertiggestellt.

- admin/dashboard.css
- admin/dashboard.php
- admin/index.php
- sidebar.php
- system/dbconnect.php
- system/destroy_session.php
- system/functions.php
- system/js/script.js
- system/login/activation.php
- system/login/login.php
Session wird nun korrekt gesetzt, die ersten Funktionen in der Sidebar sind nun vom Login-Status abhängig. Für nicht öffentlich zugängliche Bereiche (Admin Dashboard) wird die Nutzergruppe abgefragt und verglichen. Hier müssen wir uns eine bessere Lösung überlegen.
> Admin Dashboard und Session

- index.php
- install/contents/database.php
- install/contents/install.php
- install/contents/settings.php
- install/contents/welcome.php
- install/footer.php
- install/header.php
- install/index.php
- install/styles/style.css
Alle (bisher benötigten) Formulare erstellt, diese sind auch komplett nutzbar, Eingaben werden schon in variablen gespeichert. Was fehlt sind noch feinarbeiten (design, textuelle anpassungen, englische version) und die Schnittstelle bzw. Programmlogik zur Erstellung der Dateien und Datenbank.
> Erster Prototyp Installation

- content/calendar/calendar.html
Kopiert aus selfhtml-wiki. Dient nur als Beispiel.
> Beispielkalender

- content/calendar/calendar.html
- footer.php
- header.php
- index.php
- sidebar.php
- styles/style.css
Erste Version des Kalenders verfügbar. Noch keine Eventansicht o.ä. möglich. Nur Kalenderfunktion.
> Prototyp Kalender fertiggestellt

- content/calendar/calendar.html
- content/eventorganizer/main.php
- content/eventorganizer/welcome.php
Feinheiten im CSS angepasst, Kalender und Buttons besser positioniert, Beispieltext eingefügt.
> Positionierung und Willkommenstext

- styles/style.css
- system/account/account.php
- system/account/forms/deleteForm.php
- system/account/profile.php
- system/account/settings.php
Grundlage für die Formulare zum abändern der Accountdaten geschaffen.
> Aktueller Stand Profilseite

- content/gallery/carousel.php
- content/gallery/gallery.php
- content/gallery/galleryframe.php
- content/gallery/images/struc.txt
- sidebar.php
- system/sitemenu.php
Ein paar Gedanken, wie die Bildergalerie aussehen könnte.
> Galerie Grundstruktur angelegt

- admin/admin.js
- admin/dashboard.php
- admin/newsblog/createnews.php
- admin/newsblog/overview.php
- styles/style.css
- system/functions.php
- system/js/script.js
- system/login/login.php
Außerdem kleinere Verbesserungen. Es werden nun kleine Bootstrap-"Toasts" bei Fehlermeldungen und Systemnachrichten angezeigt.
> Grundstruktur und Datenbank Newsblog

- admin/dashboard.php
- admin/newsblog/contentMenu.php
- admin/scripts/admin.js
- admin/scripts/adminfunctions.php
- admin/style/dashboard.css
Anzeige der Artikel im Backend funktioniert, Links in der Sidebar funktionsfähig (haben größtenteils noch kein Ziel). Warten aber darauf, mit Inhalt befüllt zu werden :)
> Verbesserungen im Admin-Dashboard

- admin/newsblog/contentMenu.php
- admin/scripts/admin.js
- admin/scripts/adminfunctions.php
- admin/style/dashboard.css
Soweit funktionsfähig: Liste aller Artikel, optionen für wöchentlich und monatlich. Pagination funktioniert, TODO: buttons zum bearb. und löschen, weiteres Menü unterhalb Tabelle, checkboxes in der Tabelle usw.
> Backend: Liste aller Artikel + pagination

- admin/dashboard.php
- admin/newsblog/writeArticle.php
- admin/scripts/adminfunctions.php
- admin/scripts/loadContent.php
- admin/style/dashboard.css
- header.php
- system/functions.php
Rudimentär funktioniert das ganze, es fehlt noch der entscheidende letzte Schritt: Das Update-Statement. Außerdem viel Testen und Fehlerbehebung.
> Erste Schritte Artikelbearbeitung

- admin/events/content.php
- admin/events/contentMenu.php
- admin/events/createEvent.php
- admin/newsblog/content.php
- admin/newsblog/contentMenu.php
- admin/newsblog/writeArticle.php
- admin/scripts/admin.js
- admin/scripts/adminfunctions.php
- admin/scripts/loadContent.php
- admin/style/dashboard.css
- content/calendar/calendar.php
- content/calendar/calendarpage.php
- content/eventorganizer/main.php
- header.php
- index.php
- system/functions.php
- system/js/jquery.js
Ganz viel geändert, verbessert, erneuert.
Backend ist nun um einige Kalenderfunktionen größer, Neue Events erstellen, vorhandene Bearbeiten oder Löschen funktioniert nun!
Frontend hat nun eine funktionierende Kalenderansicht, bei Klick auf ein Highlight-Datum im Kalender wird dieses Event angezeigt.
jQuery wurde in das Projekt integriert und ist nun nutzbar (zumindest im Frontend, falls woanders nötig einfach Datei einbinden)
> Großes Kalenderupdate

- content/calendar/calendar.php
- content/calendar/calendarpage.php
- content/calendar/displayEvent.php
- content/calendar/enrollForm.php
- content/eventorganizer/main.php
- content/eventorganizer/welcome.php
- styles/style.css
Erste Gehversuche. Kleinere Strukturänderungen, kleinere Anzeigefehler behoben.
> Minor Changes

- admin/scripts/rights_system.php
- content/newsblog/newsblog.js
- content/newsblog/newsblog_functions.php
- content/newsblog/templates/article_template.php
- content/newsblog/templates/comment_template.php
- header.php
- index.php
- styles/style.css
- system/js/script.js
Erste Schritte Kommentarfunktion, header und sidebar geändert, Rechtesystem erweitert.
> Kommentarfunktion und Header / Sidebar-fix

- admin/newsblog/newsblog_functions.php
> deleteArticle Fix
